<?php

namespace ContainerUTNIxGH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaireControllersupprimerCommentaireApiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WAObRxp.App\Controller\CommentaireController::supprimerCommentaireApi()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WAObRxp.App\\Controller\\CommentaireController::supprimerCommentaireApi()'] = ($container->privates['.service_locator.WAObRxp'] ?? $container->load('get_ServiceLocator_WAObRxpService'))->withContext('App\\Controller\\CommentaireController::supprimerCommentaireApi()', $container);
    }
}
