<?php

namespace ContainerUTNIxGH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaireControllerlisterCommentairesApiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hAbj0.E.App\Controller\CommentaireController::listerCommentairesApi()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hAbj0.E.App\\Controller\\CommentaireController::listerCommentairesApi()'] = ($container->privates['.service_locator.hAbj0.E'] ?? $container->load('get_ServiceLocator_HAbj0_EService'))->withContext('App\\Controller\\CommentaireController::listerCommentairesApi()', $container);
    }
}
