<?php

namespace Container9BjBGDr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllerdemanderArticleService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.TnnLcbF.App\Controller\ArticleController::demanderArticle()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TnnLcbF.App\\Controller\\ArticleController::demanderArticle()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.TnnLcbF.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.TnnLcbF": it needs an instance of "App\\Entity\\Article" but this type has been excluded in "config/services.yaml".'],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'article' => 'App\\Entity\\Article',
            'mailer' => '?',
            'em' => '?',
        ]))->withContext('App\\Controller\\ArticleController::demanderArticle()', $container);
    }
}
