<?php

namespace Container9BjBGDr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaireControllermodifierCommentaireRenderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.WAObRxp.App\Controller\CommentaireController::modifierCommentaireRender()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.WAObRxp'] ?? $container->load('get_ServiceLocator_WAObRxpService'));

        if (isset($container->privates['.service_locator.WAObRxp.App\\Controller\\CommentaireController::modifierCommentaireRender()'])) {
            return $container->privates['.service_locator.WAObRxp.App\\Controller\\CommentaireController::modifierCommentaireRender()'];
        }

        return $container->privates['.service_locator.WAObRxp.App\\Controller\\CommentaireController::modifierCommentaireRender()'] = $a->withContext('App\\Controller\\CommentaireController::modifierCommentaireRender()', $container);
    }
}
