<?php

namespace Container9BjBGDr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateurControllermodifierService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.MDVvwpm.App\Controller\UtilisateurController::modifier()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MDVvwpm.App\\Controller\\UtilisateurController::modifier()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'utilisateur' => ['privates', '.errored..service_locator.MDVvwpm.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.MDVvwpm": it needs an instance of "App\\Entity\\Utilisateur" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'utilisateur' => 'App\\Entity\\Utilisateur',
            'entityManager' => '?',
            'passwordHasher' => '?',
        ]))->withContext('App\\Controller\\UtilisateurController::modifier()', $container);
    }
}
