<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOG3LxI6\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOG3LxI6/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOG3LxI6.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOG3LxI6\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOG3LxI6\App_KernelProdContainer([
    'container.build_hash' => 'OG3LxI6',
    'container.build_id' => '5c112b7a',
    'container.build_time' => 1739234593,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOG3LxI6');
