<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWURwfFl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWURwfFl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWURwfFl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWURwfFl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWURwfFl\App_KernelDevDebugContainer([
    'container.build_hash' => 'WURwfFl',
    'container.build_id' => '07e780b6',
    'container.build_time' => 1741912115,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWURwfFl');
