<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'style' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/style.css',
            ],
        ],
    ],
],

]];
