<?php

namespace ContainerOG3LxI6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Emu2TZ7Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.emu2TZ7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.emu2TZ7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation' => ['privates', '.errored..service_locator.emu2TZ7.App\\Entity\\UtilisateurArticle', NULL, 'Cannot autowire service ".service_locator.emu2TZ7": it needs an instance of "App\\Entity\\UtilisateurArticle" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'reservation' => 'App\\Entity\\UtilisateurArticle',
            'em' => '?',
        ]);
    }
}
