<?php

namespace ContainerOG3LxI6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllerdetailsService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.92uOXnH.App\Controller\ArticleController::details()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.92uOXnH.App\\Controller\\ArticleController::details()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.92uOXnH.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.92uOXnH": it needs an instance of "App\\Entity\\Article" but this type has been excluded in "config/services.yaml".'],
            'commentaireRepository' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService', true],
        ], [
            'article' => 'App\\Entity\\Article',
            'commentaireRepository' => 'App\\Repository\\CommentaireRepository',
        ]))->withContext('App\\Controller\\ArticleController::details()', $container);
    }
}
