<?php

namespace ContainerOG3LxI6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllermodifierService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.d6UE9.H.App\Controller\ArticleController::modifier()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.d6UE9.H'] ?? $container->load('get_ServiceLocator_D6UE9_HService'));

        if (isset($container->privates['.service_locator.d6UE9.H.App\\Controller\\ArticleController::modifier()'])) {
            return $container->privates['.service_locator.d6UE9.H.App\\Controller\\ArticleController::modifier()'];
        }

        return $container->privates['.service_locator.d6UE9.H.App\\Controller\\ArticleController::modifier()'] = $a->withContext('App\\Controller\\ArticleController::modifier()', $container);
    }
}
