<?php

namespace ContainerOG3LxI6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllerannulerReservationService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.emu2TZ7.App\Controller\ArticleController::annulerReservation()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.emu2TZ7.App\\Controller\\ArticleController::annulerReservation()'] = ($container->privates['.service_locator.emu2TZ7'] ?? $container->load('get_ServiceLocator_Emu2TZ7Service'))->withContext('App\\Controller\\ArticleController::annulerReservation()', $container);
    }
}
