<?php

namespace ContainerOG3LxI6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ArticleController::accueil' => ['privates', '.service_locator.rsLxjwk.App\\Controller\\ArticleController::accueil()', 'getArticleControlleraccueilService', true],
            'App\\Controller\\ArticleController::ajouter' => ['privates', '.service_locator.PrlWoMJ.App\\Controller\\ArticleController::ajouter()', 'getArticleControllerajouterService', true],
            'App\\Controller\\ArticleController::modifier' => ['privates', '.service_locator.d6UE9.H.App\\Controller\\ArticleController::modifier()', 'getArticleControllermodifierService', true],
            'App\\Controller\\ArticleController::supprimer' => ['privates', '.service_locator.d6UE9.H.App\\Controller\\ArticleController::supprimer()', 'getArticleControllersupprimerService', true],
            'App\\Controller\\ArticleController::details' => ['privates', '.service_locator.92uOXnH.App\\Controller\\ArticleController::details()', 'getArticleControllerdetailsService', true],
            'App\\Controller\\ArticleController::demanderArticle' => ['privates', '.service_locator.TnnLcbF.App\\Controller\\ArticleController::demanderArticle()', 'getArticleControllerdemanderArticleService', true],
            'App\\Controller\\ArticleController::confirmerReservation' => ['privates', '.service_locator.emu2TZ7.App\\Controller\\ArticleController::confirmerReservation()', 'getArticleControllerconfirmerReservationService', true],
            'App\\Controller\\ArticleController::annulerReservation' => ['privates', '.service_locator.emu2TZ7.App\\Controller\\ArticleController::annulerReservation()', 'getArticleControllerannulerReservationService', true],
            'App\\Controller\\AuthController::login' => ['privates', '.service_locator.bdpBLv..App\\Controller\\AuthController::login()', 'getAuthControllerloginService', true],
            'App\\Controller\\ContactController::handleContact' => ['privates', '.service_locator.j_M.nso.App\\Controller\\ContactController::handleContact()', 'getContactControllerhandleContactService', true],
            'App\\Controller\\EmailTestController::sendTestEmail' => ['privates', '.service_locator.HKv6Vyy.App\\Controller\\EmailTestController::sendTestEmail()', 'getEmailTestControllersendTestEmailService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.PtEirWk.App\\Controller\\ResetPasswordController::request()', 'getResetPasswordControllerrequestService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.qHpfPrp.App\\Controller\\ResetPasswordController::reset()', 'getResetPasswordControllerresetService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UtilisateurController::index' => ['privates', '.service_locator.tdgAvm5.App\\Controller\\UtilisateurController::index()', 'getUtilisateurControllerindexService', true],
            'App\\Controller\\UtilisateurController::create' => ['privates', '.service_locator.7SiSQCS.App\\Controller\\UtilisateurController::create()', 'getUtilisateurControllercreateService', true],
            'App\\Controller\\UtilisateurController::modifier' => ['privates', '.service_locator.MDVvwpm.App\\Controller\\UtilisateurController::modifier()', 'getUtilisateurControllermodifierService', true],
            'App\\Controller\\UtilisateurController::delete' => ['privates', '.service_locator.t7E4Eax.App\\Controller\\UtilisateurController::delete()', 'getUtilisateurControllerdeleteService', true],
            'App\\Controller\\UtilisateurController::profil' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UtilisateurController::profil()', 'getUtilisateurControllerprofilService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ArticleController:accueil' => ['privates', '.service_locator.rsLxjwk.App\\Controller\\ArticleController::accueil()', 'getArticleControlleraccueilService', true],
            'App\\Controller\\ArticleController:ajouter' => ['privates', '.service_locator.PrlWoMJ.App\\Controller\\ArticleController::ajouter()', 'getArticleControllerajouterService', true],
            'App\\Controller\\ArticleController:modifier' => ['privates', '.service_locator.d6UE9.H.App\\Controller\\ArticleController::modifier()', 'getArticleControllermodifierService', true],
            'App\\Controller\\ArticleController:supprimer' => ['privates', '.service_locator.d6UE9.H.App\\Controller\\ArticleController::supprimer()', 'getArticleControllersupprimerService', true],
            'App\\Controller\\ArticleController:details' => ['privates', '.service_locator.92uOXnH.App\\Controller\\ArticleController::details()', 'getArticleControllerdetailsService', true],
            'App\\Controller\\ArticleController:demanderArticle' => ['privates', '.service_locator.TnnLcbF.App\\Controller\\ArticleController::demanderArticle()', 'getArticleControllerdemanderArticleService', true],
            'App\\Controller\\ArticleController:confirmerReservation' => ['privates', '.service_locator.emu2TZ7.App\\Controller\\ArticleController::confirmerReservation()', 'getArticleControllerconfirmerReservationService', true],
            'App\\Controller\\ArticleController:annulerReservation' => ['privates', '.service_locator.emu2TZ7.App\\Controller\\ArticleController::annulerReservation()', 'getArticleControllerannulerReservationService', true],
            'App\\Controller\\AuthController:login' => ['privates', '.service_locator.bdpBLv..App\\Controller\\AuthController::login()', 'getAuthControllerloginService', true],
            'App\\Controller\\ContactController:handleContact' => ['privates', '.service_locator.j_M.nso.App\\Controller\\ContactController::handleContact()', 'getContactControllerhandleContactService', true],
            'App\\Controller\\EmailTestController:sendTestEmail' => ['privates', '.service_locator.HKv6Vyy.App\\Controller\\EmailTestController::sendTestEmail()', 'getEmailTestControllersendTestEmailService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.PtEirWk.App\\Controller\\ResetPasswordController::request()', 'getResetPasswordControllerrequestService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.qHpfPrp.App\\Controller\\ResetPasswordController::reset()', 'getResetPasswordControllerresetService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UtilisateurController:index' => ['privates', '.service_locator.tdgAvm5.App\\Controller\\UtilisateurController::index()', 'getUtilisateurControllerindexService', true],
            'App\\Controller\\UtilisateurController:create' => ['privates', '.service_locator.7SiSQCS.App\\Controller\\UtilisateurController::create()', 'getUtilisateurControllercreateService', true],
            'App\\Controller\\UtilisateurController:modifier' => ['privates', '.service_locator.MDVvwpm.App\\Controller\\UtilisateurController::modifier()', 'getUtilisateurControllermodifierService', true],
            'App\\Controller\\UtilisateurController:delete' => ['privates', '.service_locator.t7E4Eax.App\\Controller\\UtilisateurController::delete()', 'getUtilisateurControllerdeleteService', true],
            'App\\Controller\\UtilisateurController:profil' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\UtilisateurController::profil()', 'getUtilisateurControllerprofilService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ArticleController::accueil' => '?',
            'App\\Controller\\ArticleController::ajouter' => '?',
            'App\\Controller\\ArticleController::modifier' => '?',
            'App\\Controller\\ArticleController::supprimer' => '?',
            'App\\Controller\\ArticleController::details' => '?',
            'App\\Controller\\ArticleController::demanderArticle' => '?',
            'App\\Controller\\ArticleController::confirmerReservation' => '?',
            'App\\Controller\\ArticleController::annulerReservation' => '?',
            'App\\Controller\\AuthController::login' => '?',
            'App\\Controller\\ContactController::handleContact' => '?',
            'App\\Controller\\EmailTestController::sendTestEmail' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UtilisateurController::index' => '?',
            'App\\Controller\\UtilisateurController::create' => '?',
            'App\\Controller\\UtilisateurController::modifier' => '?',
            'App\\Controller\\UtilisateurController::delete' => '?',
            'App\\Controller\\UtilisateurController::profil' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ArticleController:accueil' => '?',
            'App\\Controller\\ArticleController:ajouter' => '?',
            'App\\Controller\\ArticleController:modifier' => '?',
            'App\\Controller\\ArticleController:supprimer' => '?',
            'App\\Controller\\ArticleController:details' => '?',
            'App\\Controller\\ArticleController:demanderArticle' => '?',
            'App\\Controller\\ArticleController:confirmerReservation' => '?',
            'App\\Controller\\ArticleController:annulerReservation' => '?',
            'App\\Controller\\AuthController:login' => '?',
            'App\\Controller\\ContactController:handleContact' => '?',
            'App\\Controller\\EmailTestController:sendTestEmail' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UtilisateurController:index' => '?',
            'App\\Controller\\UtilisateurController:create' => '?',
            'App\\Controller\\UtilisateurController:modifier' => '?',
            'App\\Controller\\UtilisateurController:delete' => '?',
            'App\\Controller\\UtilisateurController:profil' => '?',
        ]));
    }
}
