<?php

namespace ContainerOG3LxI6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateurArticleService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.emu2TZ7.App\Entity\UtilisateurArticle' shared service.
     *
     * @return \App\Entity\UtilisateurArticle
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.emu2TZ7": it needs an instance of "App\\Entity\\UtilisateurArticle" but this type has been excluded in "config/services.yaml".');
    }
}
