<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Article extends \App\Entity\Article implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null],
        "\0".parent::class."\0".'commentaires' => [parent::class, 'commentaires', null],
        "\0".parent::class."\0".'dateAjout' => [parent::class, 'dateAjout', null],
        "\0".parent::class."\0".'demandes' => [parent::class, 'demandes', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'etat' => [parent::class, 'etat', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'images' => [parent::class, 'images', null],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null],
        "\0".parent::class."\0".'ville' => [parent::class, 'ville', null],
        'categorie' => [parent::class, 'categorie', null],
        'commentaires' => [parent::class, 'commentaires', null],
        'dateAjout' => [parent::class, 'dateAjout', null],
        'demandes' => [parent::class, 'demandes', null],
        'description' => [parent::class, 'description', null],
        'etat' => [parent::class, 'etat', null],
        'id' => [parent::class, 'id', null],
        'images' => [parent::class, 'images', null],
        'statut' => [parent::class, 'statut', null],
        'titre' => [parent::class, 'titre', null],
        'utilisateur' => [parent::class, 'utilisateur', null],
        'ville' => [parent::class, 'ville', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
